#!/bin/sh
source ~/.local/share/music_fairy/func.lib
while getopts ":s:c:d:p:h" option
do
    non_zero $#OPTARG
    case $option in
        s )
            play_song $OPTARG
            exit 0
            ;;
        c )
            echo "creating playlist $OPTARG"
            create_playlist $OPTARG
            exit 0
            ;;
        d )
            delete_playlist $OPTARG
            exit 0
            ;;
        p )
            play_playlist $OPTARG
            exit 0
            ;;
        h )
            help
            exit 0
            ;;
        ? )
            echo "invalid switch"
            exit 0
            ;;
    esac
done
